# Generated by Django 3.0.5 on 2021-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField(verbose_name='price')),
                ('author', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('img', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
